#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/common/config/env.php';

defined('YII_DEBUG') or define('YII_DEBUG', (bool) env('APP_DEBUG', true));
defined('YII_ENV') or define('YII_ENV', (string) env('APP_ENV', 'dev'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';
require __DIR__ . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/console/config/main.php',
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
